### ISSUE TITLE
this code is beautiful！need paper，thanks，

### ISSUE THREAD

**Issue by zhoutao133474** [nimesh00/CellularAutomata#1]
your paper about this code is important ，I want it， thanks，of course ，if you yes，my email：ld-zt@foxmail.com

**Comment by nimesh00** [comment]
Thanks. This code is primarily the implementation of the paper: [http://www.paper.edu.cn/scholar/showpdf/MUT2MN1INTj0gx4h](url)
Some topics were referenced from other sources too for better understanding.
